#!/usr/local/bin/python

import cgi

def main():
	print "Content-type: text/html\n\n"
	form = cgi.FieldStorage()
	if form.has_key("myAge") and form["myAge"].value != "":
		theDAys = form["myAge]*365
		print "<b>Your age in days is ", theDays, "</b>"
	else:
		print "<h1>Error! Please enter your age.</h1>"

main()
